name: secure_cookie_storage
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  cookie_jar: ^4.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0-beta.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
