name: version_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  package_info_plus: ^8.0.2
  package_info_plus_platform_interface: ^3.0.1
  plugin_platform_interface: ^2.1.8
  version: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
