name: redirect_validator
description: A generic Dart client for REST APIs that handles token
  authentication. Adds Sentry integration and debug logging of requests out of
  the box.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  collection: ^1.19.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  web_links:
    path: ../web_links

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.6.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
