name: app_database
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  draft_storage:
    path: ../draft_storage
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  visited_post_storage:
    path: ../visited_post_storage

dev_dependencies:
  build_runner: ^2.6.0
  drift_dev: ^2.28.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
