name: hacker_news
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

workspace:
  - packages/analytics_consent_storage
  - packages/analytics_repository
  - packages/app
  - packages/app_client
  - packages/app_client_platform_configuration
  - packages/app_database
  - packages/app_logging
  - packages/app_ui
  - packages/authentication_api
  - packages/authentication_parser
  - packages/authentication_repository
  - packages/collapse_handler
  - packages/date_formatter
  - packages/draft_repository
  - packages/draft_storage
  - packages/feed_api
  - packages/feed_parser
  - packages/feed_repository
  - packages/link_launcher
  - packages/parser_core
  - packages/post_api
  - packages/post_parser
  - packages/post_repository
  - packages/redirect_validator
  - packages/reply_api
  - packages/reply_parser
  - packages/reply_repository
  - packages/secure_cookie_storage
  - packages/secure_user_id_storage
  - packages/settings_storage
  - packages/share_launcher
  - packages/text_parser
  - packages/thread_api
  - packages/thread_parser
  - packages/thread_repository
  - packages/version_repository
  - packages/visited_post_storage
  - packages/vote_api
  - packages/vote_repository
  - packages/web_links
