name: secure_storage
description: A Key/Value Secure Storage Client
publish_to: none

resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0-beta.4
  storage:
    path: ../storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
