name: analytics_repository
description: A repository that handles analytics.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  equatable: ^2.0.7
  firebase_analytics: ^11.4.0
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  mocktail: ^1.0.4
  recase: ^4.1.0
  storage:
    path: ../storage/storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
