name: analytics_repository
description: A repository that handles analytics.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  analytics_consent_storage:
    path: ../analytics_consent_storage
  equatable: ^2.0.7
  firebase_analytics: ^12.0.1
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  mocktail: ^1.0.4
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
