name: draft_storage
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  drift: ^2.28.0
  drift_flutter: ^0.2.5
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.28.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
