name: draft_storage
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  clock: ^1.1.2
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  equatable: ^2.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.6.0
  drift_dev: ^2.28.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
