name: storage
description: A Key/Value Storage Client for Dart.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.9.0

dev_dependencies:
  test: ^1.21.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
