name: draft_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  draft_storage:
    path: ../draft_storage
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  stream_transform: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
