name: reply_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  authentication_api:
    path: ../authentication_api
  draft_storage:
    path: ../draft_storage
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  reply_api:
    path: ../reply_api

dev_dependencies:
  build_runner: ^2.6.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
