arb-dir: lib/src/l10n
output-dir: lib/src/l10n/generated
output-class: DateFormatterLocalizations
output-localization-file: date_formatter_localizations.dart
nullable-getter: false
use-named-parameters: true
format: true
