// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJNwPKFScQ0QztBjkiPjQhXSy7Rpow4cA',
    appId: '1:803153356982:android:c5a201984d99ff73b4de17',
    messagingSenderId: '803153356982',
    projectId: 'hacker-client-6bde7',
    storageBucket: 'hacker-client-6bde7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrYtaDiftmv0BEOdwRxKTSh2bMB_UOa00',
    appId: '1:803153356982:ios:682ed7471c279541b4de17',
    messagingSenderId: '803153356982',
    projectId: 'hacker-client-6bde7',
    storageBucket: 'hacker-client-6bde7.firebasestorage.app',
    iosBundleId: 'com.lukasmirbt.hackerclient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrYtaDiftmv0BEOdwRxKTSh2bMB_UOa00',
    appId: '1:803153356982:ios:682ed7471c279541b4de17',
    messagingSenderId: '803153356982',
    projectId: 'hacker-client-6bde7',
    storageBucket: 'hacker-client-6bde7.firebasestorage.app',
    iosBundleId: 'com.lukasmirbt.hackerclient',
  );
}
