name: app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  analytics_consent_storage:
    path: ../analytics_consent_storage
  analytics_repository:
    path: ../analytics_repository
  app_client:
    path: ../app_client
  app_client_platform_configuration:
    path: ../app_client_platform_configuration
  app_database:
    path: ../app_database
  app_logging:
    path: ../app_logging
  app_ui:
    path: ../app_ui
  authentication_api:
    path: ../authentication_api
  authentication_repository:
    path: ../authentication_repository
  bloc_concurrency: ^0.3.0
  clock: ^1.1.2
  collapse_handler:
    path: ../collapse_handler
  collection: ^1.19.1
  date_formatter:
    path: ../date_formatter
  draft_repository:
    path: ../draft_repository
  draft_storage:
    path: ../draft_storage
  equatable: ^2.0.7
  feed_api:
    path: ../feed_api
  feed_parser:
    path: ../feed_parser
  feed_repository:
    path: ../feed_repository
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_inappwebview: ^6.2.0-beta.2
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  freezed_annotation: ^3.1.0
  go_router:
    git:
      url: https://github.com/LukasMirbt/packages.git
      ref: go-router/shell-route-ios-back-gesture
      path: packages/go_router
  html: ^0.15.6
  intl: ^0.20.2
  link_launcher:
    path: ../link_launcher
  nested: ^1.0.0
  plugin_platform_interface: ^2.1.8
  post_api:
    path: ../post_api
  post_parser:
    path: ../post_parser
  post_repository:
    path: ../post_repository
  provider: ^6.1.2
  redirect_validator:
    path: ../redirect_validator
  reply_api:
    path: ../reply_api
  reply_repository:
    path: ../reply_repository
  scrollable_positioned_list: ^0.3.8
  secure_cookie_storage:
    path: ../secure_cookie_storage
  secure_user_id_storage:
    path: ../secure_user_id_storage
  settings_storage:
    path: ../settings_storage
  share_launcher:
    path: ../share_launcher
  shared_preferences: ^2.5.3
  skeletonizer: ^2.0.1
  stream_transform: ^2.1.1
  super_sliver_list: ^0.4.1
  thread_api:
    path: ../thread_api
  thread_repository:
    path: ../thread_repository
  url_launcher: ^6.3.1
  version_repository:
    path: ../version_repository
  very_good_infinite_list: ^0.9.0
  visited_post_storage:
    path: ../visited_post_storage
  vote_api:
    path: ../vote_api
  vote_repository:
    path: ../vote_repository
  web_links:
    path: ../web_links

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.6.0
  fake_async: ^1.3.3
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  go_router_builder: ^4.0.1
  mockingjay: ^2.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - shorebird.yaml
