arb-dir: lib/src/l10n
output-dir: lib/src/l10n/generated
output-class: AppUiLocalizations
output-localization-file: app_ui_localizations.dart
nullable-getter: false
use-named-parameters: true
format: true
header: |
  // coverage:ignore-file
