name: app_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Pinned to avoid duplicate semantics when PR is merged
  # https://github.com/daohoangson/flutter_widget_from_html/pull/1429
  flutter_widget_from_html_core: 0.16.0
  html: ^0.15.6
  intl: ^0.20.2
  provider: ^6.1.4
  skeletonizer: ^2.0.1
  super_sliver_list: ^0.4.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter_gen:
  output: lib/src/generated/
  assets:
    outputs:
      package_parameter_enabled: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: At Hauss
      fonts:
        - asset: assets/fonts/AtHauss-Semibold.otf
          weight: 600
        - asset: assets/fonts/AtHauss-Regular.otf
          weight: 400
    - family: Noto Sans Mono
      fonts:
        - asset: assets/fonts/NotoSansMono-Regular.ttf
          weight: 400
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Italic-VariableFont.ttf
        - asset: assets/fonts/NotoSans-VariableFont.ttf
