name: app_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  collapse_handler:
    path: ../collapse_handler
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Pinned to avoid duplicate semantics when PR is merged
  # https://github.com/daohoangson/flutter_widget_from_html/pull/1429
  flutter_widget_from_html_core: 0.17.0
  html: ^0.15.6
  intl: ^0.20.2
  material_symbols_icons: ^4.2858.1
  provider: ^6.1.4
  skeletonizer:
    git:
      url: https://github.com/LukasMirbt/skeletonizer
      ref: preserve-state
  super_sliver_list: ^0.4.1

dev_dependencies:
  build_runner: ^2.6.0
  flutter_gen_runner: ^5.11.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter_gen:
  output: lib/src/generated/
  assets:
    outputs:
      package_parameter_enabled: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Noto Sans Mono
      fonts:
        - asset: assets/fonts/NotoSansMono-Regular.ttf
          weight: 400
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Italic-VariableFont.ttf
        - asset: assets/fonts/NotoSans-VariableFont.ttf
