name: link_launcher
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  url_launcher: ^6.3.0
  url_launcher_platform_interface: ^2.3.2
  web_links:
    path: ../web_links

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
