name: post_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  bloc: ^9.0.0
  collection: ^1.19.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  post_api:
    path: ../post_api

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
