name: app_logging

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "packages/app_logging/**"
      - ".github/workflows/app_logging.yaml"
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/flutter_package.yaml
    with:
      working_directory: packages/app_logging
