name: thread_api

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "packages/thread_api/**"
      - ".github/workflows/thread_api.yaml"
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/flutter_package.yaml
    with:
      working_directory: packages/thread_api
