name: web_links

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "packages/web_links/**"
      - ".github/workflows/web_links.yaml"
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/flutter_package.yaml
    with:
      working_directory: packages/web_links
